monitoring:
  delimiter: /
  pull-data:
    pull-request-list:
      - name:
        base-url:
        path:
        unit:
        interval:

spring:
  data:
    redis:
      cluster:
        max-redirects: 5
        password:
        connect-ip: 192.168.0.5
        #Millis
        refresh_period: 30000
        nodes:
          - 192.168.0.5:7001
          - 192.168.0.5:7002
          - 192.168.0.5:7003
          - 192.168.0.5:7004
          - 192.168.0.5:7005
          - 192.168.0.5:7006
  web:
    rest-template:
      max-connection: 100
      connection-per-route: 20
      evict-idle-connections: 60000
      session-timeout: 10000